#!/bin/bash
# script that runs parmeter recovery for different models
# please run it with "bash", instead of "sh"

setups="exp1 exp2"

echo $pwd
# loop through setups
for setup in $setups
do
echo working on $setup

if [ $setup == "exp1" ]
then
initialQ=0.33
else
initialQ=0.5
fi

echo initial Q = $initialQ

models="dLR_Instr fLR_Instr fLR_Eval"

# estimate the parameters (by default with 10 for betalimit and 1 for
# starting point)
#Rscript parameter_recovery/ParameterRecovery.R 10 5 $initialQ $setup

# for single models
for model in $models
do
echo working on $model

# print the outputs
Rscript parameter_recovery/Print.data.$model.R $setup

done



done